POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "csagan",
    "name": "Carl Saga",
    "password": "saranghae"
}

# {
#     "username":"root",
#     "name":"Timmy Turner",
#     "password":"lemonmelon"
# }