POST http://localhost:3001/api/login
Content-Type: application/json

//correct info
# {
#     "username": "csagan",
#     "password": "saranghae"
# }

//incorrect info
{
    "username": "csagan",
    "password": "sarang"
}